## Cleaning List of ICD10 Diagnoses with Psychotic Features

The stakeholder had given me a list of qualifying diagnoses, which I converted into a txt file to read into Python.

In [1]:
import re
import pandas as pd

# import the txt file with the qualifying ICD10 diagnoses
with open('icd10dx.txt', 'r') as dx:
    dx_read = dx.read()

# put all the lines into the list
dx_list = dx_read.split("\n")
len(dx_list)

258

In [4]:
# check the list
dx_list[10:20]

['F23 Brief Psychotic Disorder',
 'F24 Shared Psychotic Disorder',
 'F25.0 Schizoaffective Disorder, Bipolar Type',
 'F25.1 Schizoaffective Disorder, Depressive Type',
 'F25.8 Other Schizoaffective Disorders',
 'F25.9 Schizoaffective Disorder, Unspecified',
 'F28 Other Psychotic Disorder Not Due to a Substance or',
 'Known Physiological Condition',
 'F29 Unspecified Psychosis Not Due to a Substance or',
 'Known Physiological Condition']

At first glance, it appears that there are 258 diagnoses in this file, but upon closer examination of what is in our list, we can see that there are some formatting errors. 

Most diagnoses are a string with an alpha-numeric code (ICD10) followed by a description:

> 'F25.0 Schizoaffective Disorder, Bipolar Type'

However, it seems like some diagnoses with a longer description got split into two lines:

> 'F28 Other Psychotic Disorder Not Due to a Substance or'

> 'Known Physiological Condition'

Thus, this must be accounted for. We can do this by leveraging regex. Dropping these lines from the description is something we can afford since matching on ICD10 code is much more important. We can query the diagnosis description again in the SQL database.

In [5]:
# get the filtered list of lines with dx only
dx_filtered = []

for line in dx_list:
    if re.match(r"[A-Z]\d", line):
        dx_filtered.append(line)

print(len(dx_filtered))

212

After this, we need to separate the ICD10 code from the description and put this into a Pandas dataframe

In [8]:
# separate the dx codes and the dx_desc
dx_codes = []
dx_desc = []

for line in dx_filtered:
    dx_codes.append(line.split(" ")[0])
    dx_desc.append(" ".join(line.split(" ")[1:]))
    
# put into dataframe and output as csv for ease of use
dx_df = pd.DataFrame(dx_desc, index = dx_codes)
dx_df.head()
#dx_df.to_csv('dx_filtered_file.csv')

                                    0
F20.0          Paranoid Schizophrenia
F20.1      Disorganized Schizophrenia
F20.2         Catatonic Schizophrenia
F20.3  Undifferentiated Schizophrenia
F20.5          Residual Schizophrenia

I can also leverage Python to write some of SQL script for me, particularly the temp table to hold these diagnoses.

In [11]:
for dx in dx_codes:
    print("INSERT INTO #dx values ('{}')".format(dx))

INSERT INTO #dx values ('F20.0')
INSERT INTO #dx values ('F20.1')
INSERT INTO #dx values ('F20.2')
INSERT INTO #dx values ('F20.3')
INSERT INTO #dx values ('F20.5')
INSERT INTO #dx values ('F20.81')
INSERT INTO #dx values ('F20.89')
INSERT INTO #dx values ('F20.9')
INSERT INTO #dx values ('F21')
INSERT INTO #dx values ('F22')
INSERT INTO #dx values ('F23')
INSERT INTO #dx values ('F24')
INSERT INTO #dx values ('F25.0')
INSERT INTO #dx values ('F25.1')
INSERT INTO #dx values ('F25.8')
INSERT INTO #dx values ('F25.9')
INSERT INTO #dx values ('F28')
INSERT INTO #dx values ('F29')
INSERT INTO #dx values ('F30.10')
INSERT INTO #dx values ('F30.11')
INSERT INTO #dx values ('F30.12')
INSERT INTO #dx values ('F30.13')
INSERT INTO #dx values ('F30.2')
INSERT INTO #dx values ('F30.3')
INSERT INTO #dx values ('F30.4')
INSERT INTO #dx values ('F30.8')
INSERT INTO #dx values ('F30.9')
INSERT INTO #dx values ('F31.0')
INSERT INTO #dx values ('F31.10')
INSERT INTO #dx values ('F31.11')
INSERT INTO #dx values ('F31.12')
INSERT INTO #dx values ('F31.13')
INSERT INTO #dx values ('F31.2')
INSERT INTO #dx values ('F31.30')
INSERT INTO #dx values ('F31.31')
INSERT INTO #dx values ('F31.32')
INSERT INTO #dx values ('F31.4')
INSERT INTO #dx values ('F31.5')
INSERT INTO #dx values ('F31.60')
INSERT INTO #dx values ('F31.61')
INSERT INTO #dx values ('F31.62')
INSERT INTO #dx values ('F31.63')
INSERT INTO #dx values ('F31.64')
INSERT INTO #dx values ('F31.70')
INSERT INTO #dx values ('F31.71')
INSERT INTO #dx values ('F31.72')
INSERT INTO #dx values ('F31.73')
INSERT INTO #dx values ('F31.74')
INSERT INTO #dx values ('F31.75')
INSERT INTO #dx values ('F31.76')
INSERT INTO #dx values ('F31.77')
INSERT INTO #dx values ('F31.78')
INSERT INTO #dx values ('F31.81')
INSERT INTO #dx values ('F31.89')
INSERT INTO #dx values ('F31.9')
INSERT INTO #dx values ('F32.0')
INSERT INTO #dx values ('F32.1')
INSERT INTO #dx values ('F32.2')
INSERT INTO #dx values ('F32.3')
INSERT INTO #dx values ('F32.4')
INSERT INTO #dx values ('F32.5')
INSERT INTO #dx values ('F32.89')
INSERT INTO #dx values ('F32.9')
INSERT INTO #dx values ('F33.0')
INSERT INTO #dx values ('F33.1')
INSERT INTO #dx values ('F33.2')
INSERT INTO #dx values ('F33.3')
INSERT INTO #dx values ('F33.40')
INSERT INTO #dx values ('F33.41')
INSERT INTO #dx values ('F33.42')
INSERT INTO #dx values ('F33.8')
INSERT INTO #dx values ('F33.9')
INSERT INTO #dx values ('F34.0')
INSERT INTO #dx values ('F34.1')
INSERT INTO #dx values ('F34.81')
INSERT INTO #dx values ('F34.89')
INSERT INTO #dx values ('F34.9')
INSERT INTO #dx values ('F39')
INSERT INTO #dx values ('F40.00')
INSERT INTO #dx values ('F40.01')
INSERT INTO #dx values ('F40.02')
INSERT INTO #dx values ('F40.10')
INSERT INTO #dx values ('F40.11')
INSERT INTO #dx values ('F40.210')
INSERT INTO #dx values ('F40.218')
INSERT INTO #dx values ('F40.220')
INSERT INTO #dx values ('F40.228')
INSERT INTO #dx values ('F40.231')
INSERT INTO #dx values ('F40.232')
INSERT INTO #dx values ('F40.233')
INSERT INTO #dx values ('F40.240')
INSERT INTO #dx values ('F40.241')
INSERT INTO #dx values ('F40.242')
INSERT INTO #dx values ('F40.243')
INSERT INTO #dx values ('F40.248')
INSERT INTO #dx values ('F40.290')
INSERT INTO #dx values ('F40.291')
INSERT INTO #dx values ('F40.298')
INSERT INTO #dx values ('F40.8')
INSERT INTO #dx values ('F41.0')
INSERT INTO #dx values ('F41.1')
INSERT INTO #dx values ('F41.3')
INSERT INTO #dx values ('F41.8')
INSERT INTO #dx values ('F41.9')
INSERT INTO #dx values ('F42.2')
INSERT INTO #dx values ('F42.3')
INSERT INTO #dx values ('F42.4')
INSERT INTO #dx values ('F42.8')
INSERT INTO #dx values ('F42.9')
INSERT INTO #dx values ('F43.0')
INSERT INTO #dx values ('F43.10')
INSERT INTO #dx values ('F43.11')
INSERT INTO #dx values ('F43.12')
INSERT INTO #dx values ('F43.20')
INSERT INTO #dx values ('F43.21')
INSERT INTO #dx values ('F43.22')
INSERT INTO #dx values ('F43.23')
INSERT INTO #dx values ('F43.24')
INSERT INTO #dx values ('F43.25')
INSERT INTO #dx values ('F43.29')
INSERT INTO #dx values ('F44.0')
INSERT INTO #dx values ('F44.1')
INSERT INTO #dx values ('F44.4')
INSERT INTO #dx values ('F44.5')
INSERT INTO #dx values ('F44.6')
INSERT INTO #dx values ('F44.7')
INSERT INTO #dx values ('F44.81')
INSERT INTO #dx values ('F44.9')
INSERT INTO #dx values ('F45.0')
INSERT INTO #dx values ('F45.1')
INSERT INTO #dx values ('F45.22')
INSERT INTO #dx values ('F45.41')
INSERT INTO #dx values ('F45.42')
INSERT INTO #dx values ('F45.8')
INSERT INTO #dx values ('F48.1')
INSERT INTO #dx values ('F50.00')
INSERT INTO #dx values ('F50.01')
INSERT INTO #dx values ('F50.02')
INSERT INTO #dx values ('F50.2')
INSERT INTO #dx values ('F50.81')
INSERT INTO #dx values ('F50.82')
INSERT INTO #dx values ('F50.9')
INSERT INTO #dx values ('F60.0')
INSERT INTO #dx values ('F60.1')
INSERT INTO #dx values ('F60.3')
INSERT INTO #dx values ('F60.4')
INSERT INTO #dx values ('F60.5')
INSERT INTO #dx values ('F60.6')
INSERT INTO #dx values ('F60.7')
INSERT INTO #dx values ('F60.81')
INSERT INTO #dx values ('F60.9')
INSERT INTO #dx values ('F63.0')
INSERT INTO #dx values ('F63.1')
INSERT INTO #dx values ('F63.2')
INSERT INTO #dx values ('F63.3')
INSERT INTO #dx values ('F63.81')
INSERT INTO #dx values ('F63.9')
INSERT INTO #dx values ('F64.0')
INSERT INTO #dx values ('F64.2')
INSERT INTO #dx values ('F64.9')
INSERT INTO #dx values ('F65.0')
INSERT INTO #dx values ('F65.1')
INSERT INTO #dx values ('F65.2')
INSERT INTO #dx values ('F65.3')
INSERT INTO #dx values ('F65.4')
INSERT INTO #dx values ('F65.50')
INSERT INTO #dx values ('F65.51')
INSERT INTO #dx values ('F65.52')
INSERT INTO #dx values ('F65.81')
INSERT INTO #dx values ('F65.9')
INSERT INTO #dx values ('F68.10')
INSERT INTO #dx values ('F68.11')
INSERT INTO #dx values ('F68.12')
INSERT INTO #dx values ('F68.13')
INSERT INTO #dx values ('F80.82')
INSERT INTO #dx values ('F80.9')
INSERT INTO #dx values ('F84.2')
INSERT INTO #dx values ('F84.3')
INSERT INTO #dx values ('F84.5')
INSERT INTO #dx values ('F84.8')
INSERT INTO #dx values ('F84.9')
INSERT INTO #dx values ('F90.0')
INSERT INTO #dx values ('F90.1')
INSERT INTO #dx values ('F90.2')
INSERT INTO #dx values ('F90.8')
INSERT INTO #dx values ('F90.9')
INSERT INTO #dx values ('F91.1')
INSERT INTO #dx values ('F91.2')
INSERT INTO #dx values ('F91.3')
INSERT INTO #dx values ('F91.8')
INSERT INTO #dx values ('F91.9')
INSERT INTO #dx values ('F93.0')
INSERT INTO #dx values ('F93.8')
INSERT INTO #dx values ('F93.9')
INSERT INTO #dx values ('F94.0')
INSERT INTO #dx values ('F94.1')
INSERT INTO #dx values ('F98.0')
INSERT INTO #dx values ('F98.1')
INSERT INTO #dx values ('F98.21')
INSERT INTO #dx values ('F98.29')
INSERT INTO #dx values ('F98.3')
INSERT INTO #dx values ('F98.4')
INSERT INTO #dx values ('G21.0')
INSERT INTO #dx values ('G21.11')
INSERT INTO #dx values ('G24.4')
INSERT INTO #dx values ('G25.1')
INSERT INTO #dx values ('G25.70')
INSERT INTO #dx values ('G25.71')
INSERT INTO #dx values ('G25.9')
INSERT INTO #dx values ('R15.0')
INSERT INTO #dx values ('R15.9')
INSERT INTO #dx values ('R69')